name: Merge Source configs and write Source-Registry

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - '**.yml'

jobs:
  build_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install required Python packages
        run: pip install -r .github/requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Merge Source configs and write Source-Registry
        run: python .github/build_registry.py .github/registry.yml
        working-directory: ${{ github.workspace }}

      - name: Pull latest changes from remote
        run: git pull origin main

      - name: Determine next branch number
        id: next_branch_number
        run: |
          latest_branch=$(git for-each-ref --sort=-refname --format='%(refname:short)' refs/heads/release/v1.* | head -n 1)
          if [ -z "$latest_branch" ]; then
            next_number=1
          else
            latest_number=$(echo "$latest_branch" | grep -oE '[0-9]+$')
            next_number=$((latest_number + 1))
          fi
          echo "::set-output name=next_number::$next_number"
        shell: bash

      - name: Commit and push built registry on new branch
        run: |
          git config --local user.email "security@kyve.network"
          git config --local user.name "kyve-network"
          next_branch="release/v1.${{ steps.next_branch_number.outputs.next_number }}"
          git checkout -b "$next_branch"
          git add .github/registry.yml
          git commit -m "🎉 Update registry.yml"
          git push origin "$next_branch"
        working-directory: ${{ github.workspace }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: 🎉 Release new registry.yml
          committer: kyve-network <security@kyve.network>
          author: security@kyve.network
          branch: $next_branch
          delete-branch: true
          title: 🎉 New release - { {$next_branch }}
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: christopherbrumm
          reviewers: christopherbrumm, troykessler
